# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on: [push, pull_request]

# The jobs that will be run, usually in parallel
jobs:
  # A job to generate and publish code coverage
  coverage:
    # A more descriptive name of the job
    name: Test and publish test coverage
    # The OS on which the job will run
    runs-on: ubuntu-latest
    # The steps for the job, executed in sequence
    steps:
      # A GitHub action for checking out the current branch
      - uses: actions/checkout@master
      # A GitHub action to setup Node.js
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      # Run the yarn install command before proceeding
      - run: yarn install
      # A GitHub action for running tests and publishing coverage
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          # An environment variable, the value is a GitHub repo secret
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}

        with:
          # Run our `coverage` script in our `package.json`
          coverageCommand: yarn run coverage
          # By default, this looks for a `coverage` folder in the root of your project, but you may need to change this
          coverageLocations: "./coverage/clover.xml:clover"
          debug: true

      # Send a build notification email
      - name: Send email
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          # SMTP server address
          server_address: smtp.gmail.com
          # SMTP server port
          server_port: 465
          # Authenticate as this user to SMTP server
          username: ${{secrets.MAIL_USERNAME}}
          # Authenticate with this password to SMTP server
          password: ${{secrets.MAIL_PASSWORD}}
          # Subject of mail message
          subject: Github Actions build result
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body: Build job of ${{github.repository}} completed!
          # Recipients mail addresses (separated with comma)
          to: ${{secrets.BUILD_NOTICE_RECIPIENTS}}
          # Full name of mail sender (might be with an email address specified in <>)
          from: Neighborhood Chef <${{secrets.MAIL_USERNAME}}>
          # Optional content type (defaults to text/plain):
          content_type: text/html
